// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kggdhvxyexsdrzwfdqyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnZ2Rodnh5ZXhzZHJ6d2ZkcXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODI0MzcsImV4cCI6MjA2NDU1ODQzN30.17JsoNCyAhefF9454-yAsA4WQFo910-ci7v1KZO0hkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);